options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 { any; };
    allow-query { any; };
    allow-recursion { any; };
    allow-query-cache { any; };
    dnssec-validation no;
    recursion yes;
    forwarders {}; 
};

logging {
    channel stdout_log {
        stderr;
        severity debug 3;
        print-category yes;
        print-severity yes;
        print-time yes;
    };
    category default { stdout_log; };
    category queries { stdout_log; };
};

zone "sender.test" IN {
    type master;
    file "/etc/bind/sender.test.zone";
};

zone "receiver.test" IN {
    type master;
    file "/etc/bind/receiver.test.zone";
};

zone "0.89.10.in-addr.arpa" IN {
    type master;
    file "/etc/bind/10.89.0.zone";
};
